### ISSUE TITLE
Thoughts behind the project

### ISSUE THREAD

**Issue by tiagopog** [tony612/protobuf-elixir#1]
Hi @tony612, could you share the ideias you had/have behind this other implementation of protobufs to Elixir?

I'm currently working in a fork to [simplify](https://github.com/tomas-abrahamsson/gpb/issues/104) the way Exprotobuf deals with `:gpb` under the hood and now I'm wondering which are your motivations for this new project.

Cheers!

**Comment by tony612** [comment]
There're some reasons:
1. One important feature of Google Protobuf is generating code between different languages using a common proto definition. I think the way gpb does this is totally wrong. That should be done by writing a `protoc` plugin as [here](https://developers.google.com/protocol-buffers/docs/reference/other). It's OK for simple cases. But it will be hard to use if you have lots of protos.
2. For the reason 1, I thought about writing a `protoc` plugin by using gpb as the decoder/encoder. But I found it's difficult because [gpb:decode_msg/3](https://github.com/tomas-abrahamsson/gpb/blob/master/src/gpb.erl#L190) needs the message definitions to be Record format, which is hard to do in Elixir. And it also needs all `MsgDefs`, which doesn't work well with `protoc`.
3. I want to keep generated Elixir definitions simple, explicit and easy to read. What's more, I want features like Typespecs as proposed in https://github.com/tony612/grpc-elixir/issues/5. It's hard to achieve  these goals with exprotobuf.

If you think these reasons are not good enough or there're better ways to solve these. Please let me known. I'm open to other ideas only if my problems can be solved 😁

**Comment by tiagopog** [comment]
Gotcha! I think yours points make total sense :+1:

Thanks for the quick response, I'm looking forward to test it :-)

**Comment by tony612** [comment]
@tiagopog btw, I added these to the README just now.

**Comment by tiagopog** [comment]
Good idea to add this ["Why this instead of gpb or exprotobuf?"](https://github.com/tony612/protobuf-elixir#why-this-instead-of-gpb-or-exprotobuf) section.
