### ISSUE TITLE
proto3 with nil string should be valid

### ISSUE THREAD

**Issue by karlseguin** [tony612/protobuf-elixir#10]
Validation fails when assigning nil to a string, but, as far as I can tell, this should be vali.

```
syntax = "proto3";

message Test {
  string value = 1;
}
...
# raises an error
Test.encode(Test.new(value: nil))
```

This works fine in Go. Also, `encode` should return an error, not raise. There should be an `encode!` for raising.

**Comment by tony612** [comment]
I don't think it works fine in Go. In Go(proto3), you can't assign nil to a string. But I'm OK with adding `encode!` to make this easier to use. I'll add this later. Thank you!

**Comment by karlseguin** [comment]
Sorry, you're right. I'm not sure what I was thinking.

**Comment by tony612** [comment]
I thought about wether adding `encode!` to support returning status and raising error for a while. I prefer raising error when the message is invalid in `encode` directly. Because the validating is just do type checking, like that in static languages which is the basic thing. The users who use this function should think about ensuring their params are valid, otherwise error will be raised as the last line.
