### ISSUE TITLE
Should a message of default values be removed after encode?

### ISSUE THREAD

**Issue by fortunewang** [tony612/protobuf-elixir#16]
For example, the proto is:
```
message User { uint32 id = 1; }
```

A `User` of id 0 is as if a non-specified one after encode:
```
iex> u = User.new id: 0
%User{id: 0}
iex> User.encode u
""
iex> u = User.new
%User{id: 0}
iex> User.encode u
""
```

I think sometimes a explicit `User` of id 0 is needed, [exprotobuf](https://hex.pm/packages/exprotobuf) does so:
```
iex> u = User.new id: 0
%User{id: 0}
iex> User.encode u
<<8, 0>>
iex> u = User.new
%User{id: nil}
iex> User.encode u
""
```

**Comment by tony612** [comment]
It's not a bug. In proto3, you can tell wether a field is set to zero value or not set because there're default values for basic types(https://developers.google.com/protocol-buffers/docs/proto3#default). If you want to distinguish this, you can use proto2. btw, you should take an unofficial implementation(exprotobuf, gpb) as example. The official implementations(C++, Java, Go..) behave like what I do.
