### ISSUE TITLE
[question] Generate proto files automatically

### ISSUE THREAD

**Issue by mwillema** [tony612/protobuf-elixir#48]
Is there an easy way to generate the proto files automatically when calling `mix compile` or something? So I don't have to manually run the `protoc` command manually.

**Comment by jmitchell** [comment]
A built-in solution would be nice.

Meanwhile you may appreciate [this approach](https://gist.github.com/jmitchell/847543a8b366e07408f0a16bfde68f99). The `protobuf.regenerate` task calls a nix-shell/bash script which

1. installs necessary dependencies (possibly cached) in a temporary shell
2. downloads the protobuf schema from the specified (or default) URL
3. regenerates Elixir modules from the current schema

Note that the **download and generate steps are destructive** whenever there's been a change to the schema. For my purposes this is fine because I only intend to rerun it after the current copies are in version control.

[Nix](https://nixos.org/nix/) is required to run the script, but it handles the dependencies consistently (except for this package which is fetched using `mix`). I've only tested this on NixOS, but I expect it would work on other Linux distros and possibly MacOS. Windows is less likely without some effort.

**Comment by tony612** [comment]
I think you can use this https://github.com/elixir-lang/elixir_make.
